// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciefssduqzdawisijont.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZWZzc2R1cXpkYXdpc2lqb250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTg2NDcsImV4cCI6MjA2OTI3NDY0N30.V1sm5m1d6UQv1Awp67uxvAwGDjkdwlFWgV3ZuVmlHr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});